# Generated by Django 5.2.1 on 2025-06-13 09:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-sent_at'], 'verbose_name': 'Contact Message', 'verbose_name_plural': 'Contact Messages'},
        ),
        migrations.AlterModelOptions(
            name='userhistory',
            options={'ordering': ['-calculated_at'], 'verbose_name': 'User History Entry', 'verbose_name_plural': 'User History Entries'},
        ),
        migrations.RenameField(
            model_name='contactmessage',
            old_name='created_at',
            new_name='sent_at',
        ),
        migrations.RenameField(
            model_name='userhistory',
            old_name='result',
            new_name='input_data',
        ),
        migrations.RemoveField(
            model_name='userhistory',
            name='action',
        ),
        migrations.RemoveField(
            model_name='userhistory',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userhistory',
            name='calculated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userhistory',
            name='result_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userhistory',
            name='tool_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculation_history', to=settings.AUTH_USER_MODEL),
        ),
    ]
