# Generated by Django 5.2.1 on 2025-06-16 09:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_passwordresettoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userhistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'User History Entry', 'verbose_name_plural': 'User History Entries'},
        ),
        migrations.RemoveField(
            model_name='userhistory',
            name='calculated_at',
        ),
        migrations.AddField(
            model_name='userhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userhistory',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
